name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - run: pacman-key --init
      - run: pacman-key --populate archlinux
      - run: pacman --noconfirm -Sy archiso perl
      - run: pacman --noconfirm -Scc
      - run: cp -rv /usr/share/archiso/configs/releng archiso
      - run: perl -pi -e 'chomp if eof' archiso/efiboot/loader/entries/01-archiso-x86_64-linux.conf
      - run: echo " script=https://${{ github.actor }}.github.io/dotfiles" >> archiso/efiboot/loader/entries/01-archiso-x86_64-linux.conf
      - run: mkarchiso -v archiso
      - run: mv -v out/arch*.iso arch.iso
      - run: rm -rf archiso work out

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          path: arch.iso
