name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps: 
      - run: pacman-key --init
      - run: pacman-key --populate archlinux
      - run: pacman --noconfirm -Sy archiso perl
      - run: pacman --noconfirm -Scc
      - run: cp -rv /usr/share/archiso/configs/releng archiso
      - run: curl -sSLvo archiso/airootfs/etc/hosts https://raw.githubusercontent.com/maxiaof/github-hosts/master/hosts
      - run: mkdir -vp archiso/airootfs/usr/share/licenses/github-hosts
      - run: curl -sSLvo archiso/airootfs/usr/share/licenses/github-hosts/LICENSE https://raw.githubusercontent.com/maxiaof/github-hosts/master/LICENSE
      - run: perl -pi -e 'chomp if eof' archiso/efiboot/loader/entries/01-archiso-x86_64-linux.conf
      - run: echo " script=https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh" >> archiso/efiboot/loader/entries/01-archiso-x86_64-linux.conf
      - run: mkarchiso -v archiso
      - run: mv -v out/arch*.iso arch.iso
      - run: rm -rf archiso work out
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          path: arch.iso
