name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps: 
      - run: pacman-key --init
      - run: pacman-key --populate archlinux
      - run: pacman --noconfirm -Sy archiso perl
      - run: pacman --noconfirm -Scc
      - run: cp -rv /usr/share/archiso/configs/releng archiso
      - run: echo '185.199.108.133 raw.githubusercontent.com' >> archiso/airootfs/etc/hosts
      - run: echo '185.199.109.133 raw.githubusercontent.com' >> archiso/airootfs/etc/hosts
      - run: echo '185.199.110.133 raw.githubusercontent.com' >> archiso/airootfs/etc/hosts
      - run: echo '185.199.111.133 raw.githubusercontent.com' >> archiso/airootfs/etc/hosts
      - run: perl -pi -e 'chomp if eof' archiso/efiboot/loader/entries/01-archiso-x86_64-linux.conf
      - run: echo " script=https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh" >> archiso/efiboot/loader/entries/01-archiso-x86_64-linux.conf
      - run: mkarchiso -v archiso
      - run: mv -v out/arch*.iso arch.iso
      - run: rm -rf archiso work out
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          path: arch.iso
