name: Deploy static content to Surge

on:
  push:
    paths:
      - ".github/workflows/static.yml"
      - "_site/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: mv _site/install.sh _site/index.html
      - id: deployment
        run: |
          npm install -g surge
          surge _site lihua.surge.sh --token ${{ secrets.SURGE_TOKEN }}
