name: Deploy static content to Pages

on:
  push:
    paths:
      - ".github/workflows/static.yml"
      - "_site/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: mv _site/install.sh _site/index.html
      - run: npm install -g surge
      - run: surge _site lihua.surge.sh --token ${{ secrets.SURGE_TOKEN }}
