name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps: 
      - name: Test
        env:
          XDG_RUNTIME_DIR: /run/user/0
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman --noconfirm -Syuu archiso qemu-desktop edk2-ovmf perl pulseaudio
          pacman --noconfirm -Scc
          sed -i 's/timeout /&1 #/g' /usr/share/archiso/configs/releng/efiboot/loader/loader.conf
          perl -pi -e 'chomp if eof' /usr/share/archiso/configs/releng/efiboot/loader/entries/01-archiso-x86_64-linux.conf
          echo " script=https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh" >> /usr/share/archiso/configs/releng/efiboot/loader/entries/01-archiso-x86_64-linux.conf
          mkarchiso -v /usr/share/archiso/configs/releng/
          rm -rf work
          run_archiso -u -i out/*.iso
