name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps: 
      - name: Prepare arch
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
          pacman --noconfirm -Syyu
          pacman --noconfirm -Sy python-pip python-pyparted python-simple-term-menu pkgconfig gcc
      - name: Install build dependencies
        run: |
          python -m pip install --break-system-packages --upgrade pip
          pip install --break-system-packages --upgrade build twine wheel setuptools installer
          pacman-key --lsign-key farseerfc@archlinux.org
          pacman --noconfirm -Sy archinstall
      - name: Test
        run: |
          archinstall --config https://raw.githubusercontent.com/real-LiHua/dotfiles/main/user_configuration.json
