name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged --tty
    steps: 
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Test
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring archinstall
          pacman-key --lsign-key farseerfc@archlinux.org
          sed -i 's/skip_ntp": false/skip_ntp": true/' user_configuration.json
          archinstall --config user_configuration.json --silent --script guided
