name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged --tty
    steps: 
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Test
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
          pacman-key --lsign-key farseerfc@archlinux.org
          pacman --noconfirm -Syyu archinstall
          archinstall --script unattended --config user_configuration.json
