name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps: 
      - run: |
          pacman-key --init
          pacman-key --populate
          pacman -Sy --noconfirm archlinux-keyring
          pacman-key --lsign-key farseerfc@archlinux.org
          pacman -Sy --noconfirm archinstall
          archinstall --config https://raw.githubusercontent.com/real-LiHua/dotfiles/main/user_configuration.json
