name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps: 
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Test
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman --noconfirm -Sy archiso qemu-desktop edk2-ovmf
          sed -i 's/timeout /&1 #/g' /usr/share/archiso/configs/releng/efiboot/loader/loader.conf
          sed -i 's/timeout=/&1 #/g' /usr/share/archiso/configs/releng/grub/grub.cfg
          sed -i 's/timeout=/&1 #/g' /usr/share/archiso/configs/releng/grub/loopback.cfg
          mkarchiso -v /usr/share/archiso/configs/releng/
          rm -rvf work
