name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Download ArchLinux LiveCD
        run: |
          wget -nv https://geo.mirror.pkgbuild.com/iso/latest/archlinux-bootstrap-x86_64.tar.zst
          wget -nv https://archlinux.org/iso/latest/sha256sums.txt
          sha256sum -c sha256sums.txt --ignore-missing
          wget -nv https://archlinux.org/iso/latest/b2sums.txt
          b2sum -c b2sums.txt --ignore-missing
          gpg --auto-key-locate clear,wkd -v --locate-external-key pierre@archlinux.org
          wget -nv https://archlinux.org/iso/latest/archlinux-bootstrap-x86_64.tar.zst.sig
          gpg --keyserver-options auto-key-retrieve --verify archlinux-bootstrap-x86_64.tar.zst.sig archlinux-bootstrap-x86_64.tar.zst
      - name: Chroot
        run: |
          tar xf archlinux-bootstrap-x86_64.tar.zst --numeric-owner
          sudo ./root.x86_64/bin/arch-chroot root.x86_64 archinstall --config https://raw.githubusercontent.com/real-LiHua/dotfiles/main/user_configuration.json
