name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged --tty
    steps: 
      - name: Prepare arch
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
          pacman-key --lsign-key farseerfc@archlinux.org
          pacman --noconfirm -Syyu python-pip python-pyparted python-simple-term-menu pkgconfig gcc archinstall
      - name: Test
        run: |
          export TERM=linux
          archinstall --config https://raw.githubusercontent.com/real-LiHua/dotfiles/main/user_configuration.json
