name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps: 
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Test
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman --noconfirm -Sy archinstall
          pacman-key --lsign-key farseerfc@archlinux.org
          archinstall --config user_configuration.json --silent --script guided --skip-ntp
